//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_ProductsOrdered = new HashSet<tbl_ProductsOrdered>();
        }
    
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_image1 { get; set; }
        public string pro_image2 { get; set; }
        public string pro_image3 { get; set; }
        public string pro_des { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<int> pro_fk_Cat_id { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProductsOrdered> tbl_ProductsOrdered { get; set; }
    }
}
